import type { Metadata } from "next";
import "../styles/global.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Choose weights you need
  variable: "--font-montserrat", // Optional: for CSS variable usage
  display: "swap", // Optional
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
